### ISSUE TITLE
Network connection issue from Minecraft client to bungeecord server

### ISSUE THREAD

**Issue by vorburger** [dave-tucker/minecraft-demo#1]
Hey @dave-tucker I'm try to get this cool example to run locally, to perhaps use it as a starting point for some ideas I have for the future of my https://www.youtube.com/watch?v=mibW8MhenGc project.

Q1: `docker-compose --x-networking up` doesn't work for me, just print usage.. only standard `docker-compose up -d; docker-compose start` does... so what's that --x-networking for? secret flag? Or no longer needed? (want PR to edit README?)

Q2: When I start my (v1.8.9) MC Client, it does seem to see that local bungeecord in the server list, but upon trying to connect to it, or one manually added for [localhost:25565](https://github.com/dave-tucker/minecraft-demo/blob/master/docker-compose.yml#L4), fails with a java.nio.channels.UnresolvedAddressException .. `docker-compose logs -f` has:

```
01:03:17 [INFO] [michaelpapa7] <-> InitialHandler has connected
01:03:18 [INFO] [michaelpapa7] disconnected with: Could not connect to default or fallback server, please try again later: java.nio.channels.UnresolvedAddressException
01:03:18 [INFO] [michaelpapa7] -> UpstreamBridge has disconnected
```

so somehow the server is not reachable, even though a `telnet localhost 25565` shows it's open - any immediate clue, before I dig more, what I could be doing wrong? Tx!

**Comment by dave-tucker** [comment]
Q1. Yes, `--x-networking` is no longer required. It was experimental at the time that I was writing this.

Q2. I had to manually add the server to the list. `localhost:25565` should work if you are on linux, otherwise you should use the `docker-machine` IP address instead. 

One thing that may help, you may need to `docker-compose up -d` twice... there wasn't any dependency ordering (other than links) when I write this and I think that's probably where the issue is :) I'll to make a change this afternoon to fix it :D

**Comment by vorburger** [comment]
@dave-tucker yep works now. Thank you for the fix. This is cool.
